### PR TITLE
feat: Upload files over API

### PR DESCRIPTION
**Pull request by neo773**
This PR adds an option to upload files via API. It generates a secure random token for authenticating upload requests. 
This was primarily developed for automating file uploads in GitHub CI. reference [PR](https://github.com/Mudlet/Mudlet/pull/7062)

image

### CODE REVIEW

**Comment by vadi2** [comment]
We've been using WP-Downloadmanager for [Mudlet](https://www.mudlet.org/download/) over the years and the ability to add files via an API would really help simplify our release process 👍

**Comment by neo773** [comment]
@lesterchan 
Sorry to interrupt, just a gentle bump incase this got lost in your Inbox.

**Comment by lesterchan** [comment]
I would make use of [WP-API](https://developer.wordpress.org/rest-api/) to actually extend and upload via API. This MR feels  very hackish.

**Comment by vadi2** [comment]
@lesterchan we handled this improvement via a bounty and the bounty has already been paid out. Would you be interested in taking on the work to make it work via REST API?

**Comment by lesterchan** [comment]
@vadi2 Sadly I don't have the time to do it.

**Pull request closed without merging**
